[diagnostics]
enabled = true
sql_linter = true

[experimental]

[snippets]
custom_paths = []
include_default_snippets = true

[formatting]
line_length = 120

[keymap]
destructive_delete = true
preset = "default"

[keymap.overrides]

[server]
follow_symlink = false
browser = "default"

[save]
format_on_save = true
autosave_delay = 1000
autosave = "after_delay"

[package_management]
manager = "pixi"

[completion]
copilot = false
activate_on_typing = true

[mcp]
presets = []

[mcp.mcpServers]

[ai]
mode = "manual"
inline_tooltip = false
rules = ""

[ai.models]
custom_models = []
displayed_models = []

[runtime]
output_max_bytes = 8000000
on_cell_change = "autorun"
std_stream_max_bytes = 1000000
watcher_on_save = "lazy"
auto_reload = "autorun"
reactive_tests = true
default_auto_download = []
auto_instantiate = false
default_sql_output = "auto"

[language_servers.basedpyright]

[language_servers.ty]

[language_servers.pylsp]
enable_pyflakes = false
enabled = true
enable_pylint = false
enable_pydocstyle = false
enable_ruff = true
enable_mypy = false
enable_flake8 = false

[display]
theme = "dark"
reference_highlighting = false
default_width = "medium"
code_editor_font_size = 14
dataframes = "rich"
cell_output = "below"
default_table_page_size = 10
default_table_max_columns = 50
