[mcp]
presets = []

[mcp.mcpServers]

[completion]
copilot = false
activate_on_typing = true

[snippets]
custom_paths = []
include_default_snippets = true

[language_servers.ty]

[language_servers.basedpyright]

[language_servers.pylsp]
enable_pyflakes = false
enable_ruff = true
enable_mypy = false
enable_pylint = false
enabled = true
enable_pydocstyle = false
enable_flake8 = false

[formatting]
line_length = 110

[ai]
rules = ""
mode = "manual"
inline_tooltip = false

[ai.models]
custom_models = []
displayed_models = []

[save]
autosave = "after_delay"
format_on_save = true
autosave_delay = 1000

[display]
theme = "dark"
reference_highlighting = false
cell_output = "below"
dataframes = "rich"
default_table_page_size = 10
default_table_max_columns = 50
code_editor_font_size = 14
default_width = "medium"

[keymap]
preset = "default"
destructive_delete = true

[keymap.overrides]

[package_management]
manager = "pixi"

[runtime]
auto_instantiate = false
reactive_tests = true
default_auto_download = []
on_cell_change = "autorun"
watcher_on_save = "lazy"
output_max_bytes = 8000000
auto_reload = "autorun"
std_stream_max_bytes = 1000000
default_sql_output = "auto"

[experimental]

[diagnostics]
enabled = true
sql_linter = true

[server]
browser = "default"
follow_symlink = false
