[save]
autosave = "after_delay"
format_on_save = true
autosave_delay = 1000

[runtime]
reactive_tests = true
default_sql_output = "auto"
watcher_on_save = "lazy"
std_stream_max_bytes = 1000000
default_auto_download = ["ipynb"]
on_cell_change = "autorun"
auto_reload = "autorun"
output_max_bytes = 8000000
dotenv = []
auto_instantiate = true

[package_management]
manager = "pixi"

[snippets]
include_default_snippets = true
custom_paths = []

[display]
theme = "dark"
cell_output = "below"
dataframes = "rich"
code_editor_font_size = 14
default_width = "medium"
default_table_max_columns = 50
reference_highlighting = false
default_table_page_size = 10

[experimental]

[language_servers.pylsp]
enable_pylint = false
enable_pydocstyle = false
enable_flake8 = false
enable_mypy = false
enable_ruff = true
enable_pyflakes = false
enabled = true

[language_servers.basedpyright]

[language_servers.ty]

[datasources]

[ai]
inline_tooltip = false
mode = "manual"
rules = ""

[ai.models]
custom_models = []
displayed_models = []

[completion]
activate_on_typing = true
copilot = false

[server]
browser = "default"
follow_symlink = false

[formatting]
line_length = 100

[diagnostics]
sql_linter = true
enabled = true

[mcp]
presets = []

[mcp.mcpServers]

[keymap]
destructive_delete = true
preset = "default"

[keymap.overrides]
